apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zkca84v50-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:cba4acf5ed01c81bf513c1bd681f831d62fe46ac@sha256:a9617d7db231a30e9b21bd9cbaaaf7cddcee34d133770fcf35a2cfce1188cf39
          name: container-image
